# This file stores configurations for your Shopify app.

SCOPES="write_products, read_products,read_online_store_navigation, write_online_store_pages, read_online_store_pages, write_channels, read_channels, write_script_tags, read_script_tags, write_locales, read_locales, write_content, read_content, write_themes, read_themes, write_translations, read_translations, write_content_entries, read_content_entries, write_content_models, read_content_models"
